### ISSUE TITLE
PWM 2 is double-allocated

### ISSUE THREAD

**Issue by auscompgeek** [thedropbears/pyinfiniterecharge#60]
https://github.com/thedropbears/pyinfiniterecharge/blob/dddee155487a4ff8511fddf6cdcc2dab0570f444/robot.py#L56
https://github.com/thedropbears/pyinfiniterecharge/blob/dddee155487a4ff8511fddf6cdcc2dab0570f444/robot.py#L73

I know we're only using PWM motor controllers for testing, but I'm sure someone will stare at the robot for a solid hour and be confused as to why something isn't moving if we don't fix this now.

**Comment by mlists** [comment]
This should be resolved once the existing indexer code is merged in
