### ISSUE TITLE
Drivebase needs tuning in closed loop velocity mode

### ISSUE THREAD

**Issue by james-ward** [thedropbears/pyinfiniterecharge#74]
As of the commits that put the drivebase into closed loop velocity mode, it is undrivable. Lots of oscillations when coming to a stop.

**Comment by auscompgeek** [comment]
I think a significant part of the problem currently is that there is no deadzone on the joystick, so a non-zero velocity is commanded when the joystick is released.

**Comment by auscompgeek** [comment]
Should have less oscillations now that #86 is in. I only ran it at a constant 0.2 m/s however.

**Comment by james-ward** [comment]
This looks much better now
